site_name: test
site_author: NyanWhite
site_description: try
repo_name: NyanWhite/NyanWhite.github.io/
repo_url: https://NyanWhite.github.io
copyright: CC BY-NC-SA 4.0
theme:
  name: material
  language: zh
  highlightjs: true

nav:
  - index.md
  - help.md
  - self-host.md
  - license.md
