site_name: test
site_author: NyanWhite
site_description: 喵白的博客搭建测试页qwq
repo_name: NyanWhite/NyanWhite.github.io
repo_url: https://github.com/NyanWhite/NyanWhite.github.io
copyright: CC BY-NC-SA 4.0
theme:
  name: material
  language: zh
  highlightjs: true

nav:
  - index.md
  - 2023年的年度总结.md
