site_name: kmua-bot v2
site_author: Krau
site_description: kmua-bot v2 官方文档
repo_name: krau/kmua-bot
repo_url: https://github.com/krau/kmua-bot
copyright: CC BY-NC-SA 4.0
theme:
  name: material
  language: zh
  highlightjs: true

nav:
  - index.md
  - help.md
  - self-host.md
  - license.md